### ISSUE TITLE
Breaking Change in Latest Release: Missing Icons Directory

### ISSUE THREAD

**Issue by victorokech** [OyewoleOyedeji/nuxt-bootstrap-icons#7]
![Screenshot 2024-01-05 143647](https://github.com/OyewoleOyedeji/nuxt-bootstrap-icons/assets/42929043/6eba0749-3164-42c3-bd78-842c039c9846)

**Description**

The latest release of `nuxt-bootstrap-icons` introduces a breaking change causing the following error:

ENOENT: no such file or directory, scandir '<nuxt3-project-folder>/node_modules/nuxt-bootstrap-icons/node_modules/bootstrap-icons/icons'

**Steps to Reproduce**

1. Update to the latest version of `nuxt-bootstrap-icons`
2. Run your Nuxt application
3. Observe the error mentioned above.

**Expected Behaviour**

The icons directory should be present and accessible within the module's structure

**Actual Behaviour**

The `icons` directory is missing, leading to the error and preventing proper icon usage.

**Environment:**

- Nuxt version: 3.3.5
- `nuxt-bootstrap-icons` version: 1.1.0
- NodeJS version: 18.19.0
- Operating System: Windows 11 Pro 23H2

**Additional Information**

Reverting back to the previous version 1.0.3 is a temporary resolution.

**Request**

Kindly investigate this breaking change and provide a fix or guidance for addressing it. Thank you for your attention to this issue!

**Comment by oyedejioyewole** [comment]
Hmm, have you tried using version 1.1.1

**Comment by victorokech** [comment]
> Hmm, have you tried using version 1.1.1

Yes same issue

**Comment by oyedejioyewole** [comment]
@victorokech I've solved the issue with version `1.1.3`

**Comment by victorokech** [comment]
Awesome, will check it out
